@api = http://localhost:3003/users

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
"userName":"Shiri",
"userEmail":"Shiri@gmail.com",
"userPhone":"0525225956",
"userPassword":"1333",
"userPermission":"a555",
"picture":"bb77"
}

###
GET {{api}}/Shiri

###
DELETE {{api}}/Shiri